// GENERATED by scripts/sync-syllabus.mjs from the student app's course pages.
// Do not edit by hand — change the syllabus in skillofied-app and re-run the script.

export interface SyllabusModule {
  module: string;
  lessons: string[];
}

export const syllabus: Record<string, SyllabusModule[]> = {
  "java-development": [
    {
      "module": "Module 1: Introduction to Java",
      "lessons": [
        "Welcome to Java",
        "What is Java?",
        "History of Java",
        "Features of Java",
        "JDK, JRE, and JVM",
        "Installing Java",
        "Setting Up IDEs",
        "Your First Java Program"
      ]
    },
    {
      "module": "Module 2: Java Basics",
      "lessons": [
        "Java Program Structure",
        "Comments in Java",
        "Variables",
        "Data Types",
        "Type Casting",
        "Operators",
        "User Input using Scanner",
        "Output Formatting"
      ]
    },
    {
      "module": "Module 3: Control Statements",
      "lessons": [
        "if Statement",
        "if-else Statement",
        "Nested if",
        "Switch Case",
        "Ternary Operator",
        "Logical Operators"
      ]
    },
    {
      "module": "Module 4: Loops",
      "lessons": [
        "for Loop",
        "while Loop",
        "do-while Loop",
        "Nested Loops",
        "break Statement",
        "continue Statement"
      ]
    },
    {
      "module": "Module 5: Methods & Functions",
      "lessons": [
        "Introduction to Methods",
        "Method Parameters",
        "Return Types",
        "Method Overloading",
        "Recursion",
        "Variable Scope"
      ]
    },
    {
      "module": "Module 6: Arrays",
      "lessons": [
        "Introduction to Arrays",
        "One-Dimensional Arrays",
        "Two-Dimensional Arrays",
        "Array Operations",
        "Array Sorting",
        "Array Searching"
      ]
    },
    {
      "module": "Module 7: Strings",
      "lessons": [
        "Introduction to Strings",
        "String Methods",
        "StringBuilder",
        "StringBuffer",
        "String Comparison",
        "String Manipulation"
      ]
    },
    {
      "module": "Module 8: Object-Oriented Programming (OOP)",
      "lessons": [
        "Introduction to OOP",
        "Classes and Objects",
        "Constructors",
        "this Keyword",
        "Encapsulation",
        "Inheritance",
        "Polymorphism",
        "Abstraction",
        "Interfaces"
      ]
    },
    {
      "module": "Module 9: Exception Handling",
      "lessons": [
        "What are Exceptions?",
        "try-catch Block",
        "finally Block",
        "throw Keyword",
        "throws Keyword",
        "Custom Exceptions"
      ]
    },
    {
      "module": "Module 10: Collection Framework",
      "lessons": [
        "Introduction to Collections",
        "ArrayList",
        "LinkedList",
        "HashSet",
        "TreeSet",
        "HashMap",
        "TreeMap",
        "Iterator"
      ]
    },
    {
      "module": "Module 11: File Handling",
      "lessons": [
        "Introduction to Files",
        "Reading Files",
        "Writing Files",
        "BufferedReader",
        "BufferedWriter"
      ]
    },
    {
      "module": "Module 12: Multithreading",
      "lessons": [
        "Introduction to Threads",
        "Creating Threads",
        "Runnable Interface",
        "Thread Lifecycle",
        "Synchronization",
        "Thread Pool Basics"
      ]
    },
    {
      "module": "Module 13: Java 8 Features",
      "lessons": [
        "Lambda Expressions",
        "Functional Interfaces",
        "Stream API",
        "Method References",
        "Optional Class"
      ]
    },
    {
      "module": "Module 14: JDBC (database Connectivity)",
      "lessons": [
        "Introduction to JDBC",
        "Database Setup",
        "JDBC Connection",
        "CRUD Operations",
        "Prepared Statements",
        "ResultSet"
      ]
    },
    {
      "module": "Module 15: Data Structures & Algorithms in Java",
      "lessons": [
        "Time Complexity",
        "Arrays",
        "Linked Lists",
        "Stacks",
        "Queues",
        "Trees",
        "Graphs",
        "Searching Algorithms",
        "Sorting Algorithms"
      ]
    },
    {
      "module": "Module 16: Spring Boot Fundamentals",
      "lessons": [
        "Introduction to Spring Boot",
        "Spring Boot Setup",
        "REST APIs",
        "Controllers",
        "Services",
        "Repositories",
        "Dependency Injection",
        "Spring Boot Project Structure"
      ]
    },
    {
      "module": "Module 17: Spring Boot + Database",
      "lessons": [
        "MySQL/PostgreSQL Integration",
        "JPA & Hibernate",
        "Entity Mapping",
        "CRUD APIs",
        "Validation",
        "Exception Handling"
      ]
    },
    {
      "module": "Module 18: Security & Authentication",
      "lessons": [
        "Authentication Basics",
        "Authorization",
        "JWT Authentication",
        "Password Encryption",
        "Secure APIs"
      ]
    },
    {
      "module": "Module 19: Deployment",
      "lessons": [
        "Building JAR Files",
        "Environment Variables",
        "Deploying on AWS",
        "Deploying on Render",
        "Deploying with Docker"
      ]
    },
    {
      "module": "Major Projects",
      "lessons": [
        "Project 1: Student Grade Calculator",
        "Project 2: Banking System",
        "Project 3: Library Management System",
        "Project 4: Employee Management System",
        "Project 5: File Management Application",
        "Project 6: Student Management System (JDBC)",
        "Project 7: Spring Boot REST API",
        "Project 8: E-Commerce Backend",
        "Final Capstone Project"
      ]
    },
    {
      "module": "Interview Preparation",
      "lessons": [
        "Core Java Interview Questions",
        "OOP Interview Questions",
        "Collections Interview Questions",
        "Multithreading Interview Questions",
        "Spring Boot Interview Questions",
        "Coding Challenges",
        "Mock Interviews"
      ]
    }
  ],
  "frontend": [
    {
      "module": "Module 1: Introduction to Web Development",
      "lessons": [
        "Welcome to Web Development",
        "What is Web Development?",
        "How Websites Work",
        "Frontend vs Backend vs Database",
        "Frontend Development Roadmap",
        "Types of Websites",
        "Developer Tools Setup",
        "Career Opportunities"
      ]
    },
    {
      "module": "Module 2: HTML Fundamentals",
      "lessons": [
        "Introduction to HTML",
        "HTML Document Structure",
        "Headings and Paragraphs",
        "Text Formatting Tags",
        "Links and Navigation",
        "Images and Multimedia",
        "Lists (Ordered & Unordered)",
        "Tables",
        "Forms and Inputs",
        "Semantic HTML",
        "Accessibility Basics",
        "HTML Mini Project"
      ]
    },
    {
      "module": "Module 3: CSS Fundamentals",
      "lessons": [
        "Introduction to CSS",
        "CSS Syntax",
        "Selectors",
        "Colors and Backgrounds",
        "Typography",
        "Box Model",
        "Borders and Shadows",
        "Display Property",
        "Flexbox Layout",
        "Position Property",
        "CSS Variables & Hover States",
        "CSS Mini Project"
      ]
    },
    {
      "module": "Module 4: Flexbox & Grid",
      "lessons": [
        "Introduction to Flexbox",
        "Flex Container",
        "Flex Items",
        "Wrapping & Responsive Cards",
        "Introduction to CSS Grid",
        "Grid Rows & Columns",
        "Dashboard Layout with Grid Areas",
        "Flexbox & Grid Project"
      ]
    },
    {
      "module": "Module 5: Responsive Web Design",
      "lessons": [
        "What is Responsive Design",
        "Mobile First Design",
        "Media Queries",
        "Responsive Navigation",
        "Responsive Images",
        "Responsive Layouts",
        "Responsive Website Project"
      ]
    },
    {
      "module": "Module 6: JavaScript Fundamentals",
      "lessons": [
        "Introduction to JavaScript",
        "Variables",
        "Data Types",
        "Operators",
        "Conditional Statements",
        "Loops",
        "Functions",
        "Arrays",
        "Objects",
        "Scope",
        "Hoisting",
        "JavaScript Exercises"
      ]
    },
    {
      "module": "Module 7: DOM Manipulation & Events",
      "lessons": [
        "Introduction to DOM",
        "Selecting Elements",
        "Updating Elements",
        "Creating Elements",
        "Event Listeners",
        "Form Validation",
        "Local Storage",
        "Session Storage",
        "Todo App Project"
      ]
    },
    {
      "module": "Module 8: Modern JavaScript (ES6+)",
      "lessons": [
        "let vs const",
        "Arrow Functions",
        "Template Literals",
        "Destructuring",
        "Spread Operator",
        "Rest Operator",
        "Default Parameters",
        "Modules",
        "Classes",
        "Object-Oriented JavaScript"
      ]
    },
    {
      "module": "Module 9: Asynchronous JavaScript",
      "lessons": [
        "Synchronous vs Asynchronous",
        "Callbacks",
        "Promises",
        "Async/Await",
        "Fetch API",
        "Error Handling",
        "API Integration",
        "Weather App Project"
      ]
    },
    {
      "module": "Module 10: Git & GitHub",
      "lessons": [
        "Introduction to Git",
        "Installing Git",
        "Git Commands",
        "Creating Repositories",
        "GitHub Basics",
        "Branching",
        "Merging",
        "Pull Requests"
      ]
    },
    {
      "module": "Module 11: Introduction to React",
      "lessons": [
        "What is React",
        "Installing React with Vite",
        "Project Structure",
        "JSX",
        "React Components",
        "Props",
        "Component Reusability",
        "React Mini Project"
      ]
    },
    {
      "module": "Module 12: React State Management",
      "lessons": [
        "State Introduction",
        "useState Hook",
        "Event Handling",
        "Forms in React",
        "Conditional Rendering",
        "Lists and Keys",
        "Counter App Project"
      ]
    },
    {
      "module": "Module 13: React Hooks",
      "lessons": [
        "useEffect",
        "useRef",
        "useMemo",
        "useCallback",
        "Custom Hooks",
        "Hooks Project"
      ]
    },
    {
      "module": "Module 14: React Router",
      "lessons": [
        "Routing Basics",
        "Browser Router",
        "Route Parameters",
        "Nested Routes",
        "Protected Routes",
        "Routing Project"
      ]
    },
    {
      "module": "Module 15: React API Integration",
      "lessons": [
        "Fetching Data",
        "Loading States",
        "Error States",
        "CRUD Operations",
        "Authentication UI",
        "Movie App Project"
      ]
    },
    {
      "module": "Module 16: Advanced React",
      "lessons": [
        "Context API",
        "Reducers",
        "Zustand Basics",
        "Redux Toolkit Basics",
        "Performance Optimization",
        "Advanced Project"
      ]
    },
    {
      "module": "Module 17: Deployment & Optimization",
      "lessons": [
        "Build Process",
        "Environment Variables",
        "Deploying on Vercel",
        "Deploying on Netlify",
        "Custom Domain Setup",
        "SEO Basics"
      ]
    },
    {
      "module": "Major Projects",
      "lessons": [
        "Project 1: Personal Portfolio Website",
        "Project 2: Responsive Landing Page",
        "Project 3: Calculator App",
        "Project 4: Todo App",
        "Project 5: Weather Application",
        "Project 6: Movie Search Application",
        "Project 7: E-Commerce Frontend",
        "Project 8: Admin Dashboard",
        "Final Capstone Project"
      ]
    },
    {
      "module": "Interview Preparation",
      "lessons": [
        "HTML & CSS Questions",
        "JavaScript Questions",
        "React Questions",
        "Performance & Tooling Questions",
        "Coding Challenges",
        "Mock Interviews"
      ]
    }
  ],
  "sql": [
    {
      "module": "Module 1: Introduction & Fundamentals",
      "lessons": [
        "What is Data?",
        "File system vs Database",
        "What is DBMS & RDBMS?",
        "SQL vs NoSQL",
        "Popular Databases",
        "Installing PostgreSQL/MySQL",
        "Database Architecture"
      ]
    },
    {
      "module": "Module 2: Database Design Fundamentals",
      "lessons": [
        "Database, Schema, Tables",
        "Rows, Columns, Records",
        "SQL Data Types",
        "Constraints (PK, FK, etc.)"
      ]
    },
    {
      "module": "Module 3: SQL Commands Deep Dive",
      "lessons": [
        "DDL (CREATE, ALTER, DROP)",
        "DML (INSERT, UPDATE, DELETE)",
        "DQL (SELECT, WHERE, LIMIT)"
      ]
    },
    {
      "module": "Module 4: Filtering & Operators",
      "lessons": [
        "Comparison Operators",
        "Logical Operators",
        "Advanced Filtering (IN, LIKE)"
      ]
    },
    {
      "module": "Module 5: SQL Functions",
      "lessons": [
        "String Functions",
        "Numeric Functions",
        "Date Functions"
      ]
    },
    {
      "module": "Module 6: Aggregation & Grouping",
      "lessons": [
        "Aggregate Functions",
        "GROUP BY & HAVING"
      ]
    },
    {
      "module": "Module 7: SQL Joins",
      "lessons": [
        "INNER JOIN",
        "LEFT & RIGHT JOIN",
        "FULL, SELF, CROSS JOIN"
      ]
    },
    {
      "module": "Module 8: Subqueries",
      "lessons": [
        "Single & Multiple Row Subqueries",
        "Nested Queries & Operators"
      ]
    },
    {
      "module": "Module 9: Advanced SQL Concepts",
      "lessons": [
        "Views",
        "Indexing (B-Tree, Composite)",
        "Performance & EXPLAIN"
      ]
    },
    {
      "module": "Module 10: Transactions & ACID",
      "lessons": [
        "Transactions Basics",
        "ACID Properties",
        "Rollback & Savepoints",
        "Locks & Deadlocks"
      ]
    },
    {
      "module": "Module 11: Stored Procedures",
      "lessons": [
        "Functions vs Procedures",
        "Parameters & Returns",
        "PL/pgSQL basics"
      ]
    },
    {
      "module": "Module 12: Database Relationships",
      "lessons": [
        "One-to-One",
        "One-to-Many",
        "Many-to-Many",
        "ER Diagrams"
      ]
    },
    {
      "module": "Module 13: Normalization",
      "lessons": [
        "Database Anomalies",
        "1NF, 2NF, 3NF, BCNF"
      ]
    },
    {
      "module": "Module 14: PostgreSQL Advanced",
      "lessons": [
        "UUID, JSONB, Arrays, ENUM",
        "CTE & Recursive Query",
        "Window Functions"
      ]
    },
    {
      "module": "Module 15: SQL for Backend Developers",
      "lessons": [
        "Node.js + SQL Connections",
        "ORM vs Raw SQL (Prisma/TypeORM)",
        "Migrations & Seeders"
      ]
    },
    {
      "module": "Module 16: Real World Projects",
      "lessons": [
        "Project 1: Student Management DB",
        "Project 2: E-Commerce DB",
        "Project 3: LMS Database"
      ]
    },
    {
      "module": "Module 17: Interview Preparation",
      "lessons": [
        "Beginner: 50+ Questions",
        "Intermediate: Joins & Aggregations",
        "Advanced: Optimization & Indexing",
        "Company Level Practice"
      ]
    },
    {
      "module": "Final Capstone Project",
      "lessons": [
        "Udemy + HackerRank Clone DB"
      ]
    }
  ],
  "golang": [
    {
      "module": "Module 1: Introduction to Golang",
      "lessons": [
        "Welcome to Golang",
        "What is Go?",
        "History of Go",
        "Why Learn Go?",
        "Features of Go",
        "Installing Go",
        "Setting Up VS Code",
        "Your First Go Program"
      ]
    },
    {
      "module": "Module 2: Go Fundamentals",
      "lessons": [
        "Program Structure",
        "Variables",
        "Constants",
        "Data Types",
        "Type Conversion",
        "Operators",
        "User Input",
        "Output Formatting"
      ]
    },
    {
      "module": "Module 3: Control Flow",
      "lessons": [
        "if Statement",
        "if-else Statement",
        "Switch Statement",
        "for Loop",
        "break & continue",
        "Labels"
      ]
    },
    {
      "module": "Module 4: Functions",
      "lessons": [
        "Functions",
        "Parameters",
        "Multiple Return Values",
        "Named Return Values",
        "Variadic Functions",
        "Anonymous Functions",
        "Closures",
        "Recursion"
      ]
    },
    {
      "module": "Module 5: Arrays, Slices & Maps",
      "lessons": [
        "Arrays",
        "Slices",
        "Slice Operations",
        "Maps",
        "Iterating Collections",
        "Practical Examples"
      ]
    },
    {
      "module": "Module 6: Structs & Methods",
      "lessons": [
        "Structs",
        "Methods",
        "Embedded Structs",
        "Composition",
        "JSON Tags",
        "Best Practices"
      ]
    },
    {
      "module": "Module 7: Interfaces",
      "lessons": [
        "Introduction to Interfaces",
        "Implementing Interfaces",
        "Empty Interface",
        "Type Assertions",
        "Type Switches",
        "Real-World Examples"
      ]
    },
    {
      "module": "Module 8: Error Handling",
      "lessons": [
        "Errors in Go",
        "Creating Custom Errors",
        "panic",
        "defer",
        "recover",
        "Error Wrapping"
      ]
    },
    {
      "module": "Module 9: Packages & Modules",
      "lessons": [
        "Packages",
        "Go Modules",
        "Importing Packages",
        "Creating Packages",
        "Package Organization"
      ]
    },
    {
      "module": "Module 10: File Handling",
      "lessons": [
        "Reading Files",
        "Writing Files",
        "Directories",
        "JSON Files",
        "CSV Files",
        "Logging"
      ]
    },
    {
      "module": "Module 11: Concurrency",
      "lessons": [
        "Introduction to Goroutines",
        "Channels",
        "Buffered Channels",
        "Select Statement",
        "WaitGroup",
        "Mutex",
        "Context Package",
        "Worker Pools"
      ]
    },
    {
      "module": "Module 12: Testing",
      "lessons": [
        "Introduction to Testing",
        "Unit Testing",
        "Table-Driven Tests",
        "Benchmark Testing",
        "Mocking Basics"
      ]
    },
    {
      "module": "Module 13: HTTP & REST APIs",
      "lessons": [
        "HTTP Package",
        "Web Server",
        "Routing",
        "Request Handling",
        "JSON APIs",
        "Middleware",
        "API Versioning"
      ]
    },
    {
      "module": "Module 14: Databases",
      "lessons": [
        "SQL Basics",
        "PostgreSQL Setup",
        "Database Connections",
        "CRUD Operations",
        "Transactions",
        "Migrations",
        "Repository Pattern"
      ]
    },
    {
      "module": "Module 15: Building APIs with Gin",
      "lessons": [
        "Introduction to Gin",
        "Project Structure",
        "Routing",
        "Controllers",
        "Services",
        "Middleware",
        "Validation",
        "Authentication"
      ]
    },
    {
      "module": "Module 16: Authentication & Security",
      "lessons": [
        "Password Hashing",
        "JWT Authentication",
        "Authorization",
        "Refresh Tokens",
        "API Security",
        "CORS"
      ]
    },
    {
      "module": "Module 17: Microservices Basics",
      "lessons": [
        "What are Microservices?",
        "Service Communication",
        "gRPC Basics",
        "Message Queues",
        "Dockerizing Services",
        "Service Discovery"
      ]
    },
    {
      "module": "Module 18: Deployment & DevOps",
      "lessons": [
        "Building Executables",
        "Environment Variables",
        "Docker",
        "Docker Compose",
        "AWS EC2 Deployment",
        "CI/CD Basics"
      ]
    },
    {
      "module": "Major Projects",
      "lessons": [
        "Project 1: CLI Calculator",
        "Project 2: Student Management",
        "Project 3: File Manager CLI",
        "Project 4: Task Manager API",
        "Project 5: URL Shortener API",
        "Project 6: Authentication Service",
        "Project 7: E-Commerce REST API",
        "Project 8: Blog Backend API",
        "Capstone: LMS Backend"
      ]
    },
    {
      "module": "Interview Preparation",
      "lessons": [
        "Go Language Q&A",
        "Concurrency & Channels",
        "REST API Design",
        "Database & SQL",
        "System Design Basics",
        "Coding Challenges",
        "Mock Interviews"
      ]
    }
  ],
  "genai": [
    {
      "module": "Module 1: Python & AI Foundations",
      "lessons": [
        "Why Python Runs GenAI",
        "Data Structures You Will Use",
        "Functions, Comprehensions, Types",
        "Classes and Dataclasses",
        "Virtual Environments",
        "Async Python and HTTP",
        "JSON and REST Fundamentals"
      ]
    },
    {
      "module": "Module 2: Machine Learning Essentials",
      "lessons": [
        "What Machine Learning Is",
        "Supervised and Unsupervised",
        "Splitting Data and Overfitting",
        "Features, Labels, Text as Numbers",
        "Measuring Quality"
      ]
    },
    {
      "module": "Module 3: LLM Fundamentals",
      "lessons": [
        "What an LLM Is",
        "Tokens and the Context Window",
        "Transformers and Attention",
        "Temperature and Top-p",
        "Hallucination",
        "Calling a Model API"
      ]
    },
    {
      "module": "Module 4: Prompt Engineering",
      "lessons": [
        "Anatomy of a Prompt",
        "Zero-shot, Few-shot, Role",
        "Structured Output",
        "Chain-of-Thought and Reasoning",
        "Templates and Versioning",
        "Prompt Injection"
      ]
    },
    {
      "module": "Module 5: Embeddings & Vector Search",
      "lessons": [
        "From Text to Vectors",
        "Similarity Metrics",
        "Chunking Strategy",
        "Metadata and Filtering",
        "Vector Databases"
      ]
    },
    {
      "module": "Module 6: Retrieval-Augmented Generation",
      "lessons": [
        "Why RAG",
        "The Ingestion Pipeline",
        "Retrieval and Reranking",
        "Context and Citations",
        "Evaluating RAG",
        "Reducing Hallucination"
      ]
    },
    {
      "module": "Module 7: AI Agents",
      "lessons": [
        "What Makes Something an Agent",
        "Tools and Function Calling",
        "The Agent Loop",
        "Memory",
        "Multi-Agent Systems",
        "Safety and Human-in-the-Loop"
      ]
    },
    {
      "module": "Module 8: Multimodal GenAI",
      "lessons": [
        "Beyond Text",
        "Speech to Text",
        "Text to Speech and Streaming",
        "Vision",
        "Voice Agent Architecture"
      ]
    },
    {
      "module": "Module 9: Fine-Tuning",
      "lessons": [
        "Prompting vs RAG vs Fine-tuning",
        "Preparing the Dataset",
        "Instruction Tuning",
        "LoRA, QLoRA and PEFT",
        "Evaluating and When Not To"
      ]
    },
    {
      "module": "Module 10: Production GenAI",
      "lessons": [
        "Serving Architecture",
        "Streaming Responses",
        "Token Cost",
        "Caching",
        "Retries, Timeouts, Fallback",
        "Rate Limits and Concurrency"
      ]
    },
    {
      "module": "Module 11: LLMOps",
      "lessons": [
        "Why LLMOps Exists",
        "Tracing",
        "Evaluation Harnesses",
        "RAG and Hallucination Evaluation",
        "Guardrails and Security",
        "Monitoring in Production"
      ]
    },
    {
      "module": "Module 12: Forward Deployed Engineering",
      "lessons": [
        "What an FDE Does",
        "Requirement Gathering",
        "Architecture and Scoping",
        "Data Integration and Auth",
        "Customer Environments",
        "Communicating Trade-offs"
      ]
    },
    {
      "module": "Portfolio Projects",
      "lessons": [
        "Project 1: Enterprise Document RAG",
        "Project 2: AI Coding Assistant",
        "Project 3: AI Voice Agent",
        "Project 4: Multi-Agent Research Platform",
        "Project 5: Enterprise AI Platform (Capstone)"
      ]
    },
    {
      "module": "Interview Preparation",
      "lessons": [
        "LLM Fundamentals",
        "RAG and Retrieval",
        "Agents and Tools",
        "Production and Cost",
        "System Design",
        "Forward Deployed Engineering"
      ]
    }
  ],
  "digital-marketing": [
    {
      "module": "Module 1: The Digital Marketing Funnel",
      "lessons": [
        "AIDA Model & Customer Value Journey",
        "Defining Target Personas & Segments",
        "Mapping Marketing Channels to Goals"
      ]
    },
    {
      "module": "Module 2: Social Media Marketing & Organic Growth",
      "lessons": [
        "Content Pillars & Scheduling",
        "Algorithm Optimization",
        "Community Management & Engagement"
      ]
    },
    {
      "module": "Module 3: Pay-Per-Click (PPC) Advertising",
      "lessons": [
        "Google Search Ads Campaign Setup",
        "Meta Ads Manager",
        "Bidding, Budgets & Retargeting"
      ]
    },
    {
      "module": "Module 4: Email Marketing Automation",
      "lessons": [
        "Lead Magnet Design & List Growth",
        "Writing High-Open-Rate Sequences",
        "Behavioral Triggers & Workflows"
      ]
    },
    {
      "module": "Module 5: Conversion Rate Optimization (CRO)",
      "lessons": [
        "Landing Page Best Practices",
        "A/B Testing Frameworks & Tools",
        "Heatmaps & Session Analysis"
      ]
    },
    {
      "module": "Module 6: Measurement, Analytics & Attribution",
      "lessons": [
        "Reading GA4 Without Getting Lost",
        "UTM Tracking & Clean Campaign Data",
        "Attribution & the Monthly Report"
      ]
    },
    {
      "module": "Module 7: Content, Video & Partnerships",
      "lessons": [
        "Content Marketing That Feeds Every Channel",
        "Short-Form Video & Creative Testing",
        "Influencers, Affiliates & Messaging Channels"
      ]
    },
    {
      "module": "Module 8: AI in Digital Marketing",
      "lessons": [
        "Where AI Helps and Where It Fails",
        "AI for Research, Copy & Creative",
        "AI for Analysis, Reporting & Its Limits"
      ]
    },
    {
      "module": "Module 9: Capstone & Career",
      "lessons": [
        "The Capstone Campaign Plan",
        "Presenting Results & Building a Portfolio",
        "Career Paths & Interview Preparation"
      ]
    }
  ],
  "seo": [
    {
      "module": "Module 1: AI Search Foundations — GEO, LLM SEO & AEO",
      "lessons": [
        "How AI Search Engines Answer Questions",
        "GEO, LLM SEO and AEO Compared",
        "Why Classic SEO Still Decides AI Visibility"
      ]
    },
    {
      "module": "Module 2: Optimising a Page for AI Answers",
      "lessons": [
        "Answer-First Content Structure",
        "Structured Content vs Structured Data",
        "One Page for AEO, GEO and SEO"
      ]
    },
    {
      "module": "Module 3: Training AI to Find and Cite You",
      "lessons": [
        "Auditing What AI Says About You",
        "About, Contact and Source Pages AI Can Trust",
        "How AI Models Actually Learn"
      ]
    },
    {
      "module": "Module 4: Crawlability for AI Crawlers",
      "lessons": [
        "How Crawling Works for Search and AI Bots",
        "robots.txt Mistakes That Block AI",
        "llms.txt: Writing and Verifying It"
      ]
    },
    {
      "module": "Module 5: Reputation — E-E-A-T and Entity Authority",
      "lessons": [
        "Google E-E-A-T Explained",
        "Building a Consistent Entity Across the Web",
        "Mentions in Databases, Forums and Communities"
      ]
    },
    {
      "module": "Module 6: Digital PR — Earning Mentions That Train AI",
      "lessons": [
        "Why Mentions Move AI Answers",
        "Writing a Press Release for Humans, Search and AI",
        "Distribution, Follow-Up and Measuring Coverage"
      ]
    },
    {
      "module": "Module 7: AI-Assisted Technical SEO",
      "lessons": [
        "Building an SEO-Ready Site with AI Tools",
        "FAQ Schema, Interlinking and Long-Tail Coverage",
        "Page Speed and Core Web Vitals with AI Help"
      ]
    },
    {
      "module": "Module 8: Measuring AI Visibility and Staying Ahead",
      "lessons": [
        "Tracking Citations and Brand Mentions in AI Answers",
        "Google AI Overviews and AI Mode",
        "Ethics, Limits and What Comes Next"
      ]
    }
  ],
  "testing": [
    {
      "module": "Module 1: Introduction to Software Testing",
      "lessons": [
        "Welcome to Software Testing",
        "What is Software Testing?",
        "Why Software Testing is Important",
        "Software Development Life Cycle (SDLC)",
        "Software Testing Life Cycle (STLC)",
        "Roles and Responsibilities of a QA Engineer",
        "Types of Software Testing",
        "Career Roadmap for QA Engineers"
      ]
    },
    {
      "module": "Module 2: Software Testing Fundamentals",
      "lessons": [
        "Testing Principles",
        "Test Levels",
        "Functional Testing",
        "Non-Functional Testing",
        "Black Box Testing",
        "White Box Testing",
        "Grey Box Testing",
        "Verification vs Validation"
      ]
    },
    {
      "module": "Module 3: Test Case Design",
      "lessons": [
        "What is a Test Case?",
        "Test Scenario vs Test Case",
        "Test Plan",
        "Test Strategy",
        "Test Data Preparation",
        "Boundary Value Analysis",
        "Equivalence Partitioning",
        "Decision Table Testing",
        "State Transition Testing",
        "Error Guessing"
      ]
    },
    {
      "module": "Module 4: Defect Management",
      "lessons": [
        "What is a Bug?",
        "Bug Life Cycle",
        "Severity vs Priority",
        "Writing Bug Reports",
        "Defect Tracking Tools",
        "Bug Reporting Best Practices"
      ]
    },
    {
      "module": "Module 5: Agile Testing",
      "lessons": [
        "Introduction to Agile",
        "Scrum Framework",
        "Sprint Planning",
        "Daily Stand-up",
        "Sprint Review",
        "Sprint Retrospective",
        "QA in Agile Teams"
      ]
    },
    {
      "module": "Module 6: API Testing",
      "lessons": [
        "What is an API?",
        "REST APIs",
        "HTTP Methods",
        "Status Codes",
        "JSON Basics",
        "API Testing using Postman",
        "Environment Variables",
        "API Collections",
        "API Automation Basics",
        "API Testing Project"
      ]
    },
    {
      "module": "Module 7: Database Testing",
      "lessons": [
        "Introduction to Databases",
        "SQL Basics",
        "SELECT Queries",
        "INSERT, UPDATE & DELETE",
        "JOIN Operations",
        "Database Validation",
        "Data Integrity Testing"
      ]
    },
    {
      "module": "Module 8: Web Automation with Selenium",
      "lessons": [
        "Introduction to Selenium",
        "Selenium WebDriver",
        "Locators",
        "Browser Commands",
        "Handling Forms",
        "Waits",
        "Alerts & Windows",
        "Frames & iFrames",
        "Dropdowns",
        "File Upload & Download",
        "Selenium Project"
      ]
    },
    {
      "module": "Module 9: Test Automation Frameworks",
      "lessons": [
        "TestNG",
        "JUnit Basics",
        "Maven",
        "Page Object Model (POM)",
        "Data-Driven Framework",
        "Hybrid Framework",
        "Logging & Reporting",
        "Framework Project"
      ]
    },
    {
      "module": "Module 10: Performance Testing",
      "lessons": [
        "Performance Testing Basics",
        "Load Testing",
        "Stress Testing",
        "Spike Testing",
        "Endurance Testing",
        "Apache JMeter",
        "Performance Project"
      ]
    },
    {
      "module": "Module 11: Mobile Testing",
      "lessons": [
        "Mobile Testing Basics",
        "Android Testing",
        "iOS Testing",
        "Appium Introduction",
        "Mobile Automation"
      ]
    },
    {
      "module": "Module 12: Security Testing Basics",
      "lessons": [
        "Security Fundamentals",
        "Authentication Testing",
        "Authorization Testing",
        "OWASP Top 10",
        "Basic Vulnerability Testing"
      ]
    },
    {
      "module": "Module 13: CI/CD for Testers",
      "lessons": [
        "Introduction to CI/CD",
        "Git for Testers",
        "Jenkins Basics",
        "Running Automated Tests",
        "Test Reports",
        "Continuous Testing"
      ]
    },
    {
      "module": "Module 14: AI in Software Testing",
      "lessons": [
        "AI in Testing",
        "AI Test Case Generation",
        "AI Bug Analysis",
        "Self-Healing Automation",
        "AI Testing Tools",
        "Future of QA",
        "AI Testing Project"
      ]
    },
    {
      "module": "Module 15: Capstone Projects",
      "lessons": [
        "Project 1: E-Commerce Website Testing",
        "Project 2: Banking Application Testing",
        "Project 3: LMS Website Testing",
        "Project 4: HMS Website Testing",
        "Project 5: API Testing Suite",
        "Project 6: Selenium Automation Framework",
        "Final Industry Capstone Project"
      ]
    },
    {
      "module": "Interview Preparation",
      "lessons": [
        "Manual Testing Interview Questions",
        "Selenium Interview Questions",
        "API Testing Interview Questions",
        "SQL Interview Questions",
        "Agile Interview Questions",
        "Automation Framework Questions",
        "HR Interview Questions",
        "Resume Building",
        "Mock Interviews",
        "Coding & Practical Assessments"
      ]
    }
  ],
  "full-stack": [
    {
      "module": "Java Development",
      "lessons": [
        "Introduction to Java",
        "Java Basics",
        "Control Statements",
        "Loops",
        "Methods & Functions",
        "Arrays",
        "Strings",
        "Object-Oriented Programming (OOP)",
        "Exception Handling",
        "Collection Framework",
        "File Handling",
        "Multithreading",
        "Java 8 Features",
        "JDBC (database Connectivity)",
        "Data Structures & Algorithms in Java",
        "Spring Boot Fundamentals",
        "Spring Boot + Database",
        "Security & Authentication",
        "Deployment"
      ]
    },
    {
      "module": "Front-End Technologies",
      "lessons": [
        "Introduction to Web Development",
        "HTML Fundamentals",
        "CSS Fundamentals",
        "Flexbox & Grid",
        "Responsive Web Design",
        "JavaScript Fundamentals",
        "DOM Manipulation & Events",
        "Modern JavaScript (ES6+)",
        "Asynchronous JavaScript",
        "Git & GitHub",
        "Introduction to React",
        "React State Management",
        "React Hooks",
        "React Router",
        "React API Integration",
        "Advanced React",
        "Deployment & Optimization"
      ]
    },
    {
      "module": "Mastering SQL",
      "lessons": [
        "Introduction & Fundamentals",
        "Database Design Fundamentals",
        "SQL Commands Deep Dive",
        "Filtering & Operators",
        "SQL Functions",
        "Aggregation & Grouping",
        "SQL Joins",
        "Subqueries",
        "Advanced SQL Concepts",
        "Transactions & ACID",
        "Stored Procedures",
        "Database Relationships",
        "Normalization",
        "PostgreSQL Advanced",
        "SQL for Backend Developers",
        "Real World Projects",
        "Interview Preparation"
      ]
    },
    {
      "module": "GenAI & Forward Deployed Engineering",
      "lessons": [
        "Python & AI Foundations",
        "Machine Learning Essentials",
        "LLM Fundamentals",
        "Prompt Engineering",
        "Embeddings & Vector Search",
        "Retrieval-Augmented Generation",
        "AI Agents",
        "Multimodal GenAI",
        "Fine-Tuning",
        "Production GenAI",
        "LLMOps",
        "Forward Deployed Engineering"
      ]
    }
  ]
};
